-- 코드를 입력하세요
-- SELECT T.FLAVOR
-- FROM (SELECT F.FLAVOR, F.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL
#    FROM FIRST_HALF F 
#    JOIN JULY J
#    ON F.FLAVOR = J.FLAVOR
#    ORDER BY TOTAL DESC) T
# LIMIT 3

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) J
  ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3;